language: ruby
cache:
  - bundler
  - pip
rvm:
  - 2.5
before_script:
  - pip install --user html5validator
script: ./script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: script
  script: ./script/deploy
  skip_cleanup: true
  on:
    branch: master
